// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLoTW0Gj_YKOPUqwic4NLl9J1bHR8zpRE',
    appId: '1:258703453258:web:f4357fca58e694d56a0ab3',
    messagingSenderId: '258703453258',
    projectId: 'course-project-f4c51',
    authDomain: 'course-project-f4c51.firebaseapp.com',
    storageBucket: 'course-project-f4c51.appspot.com',
    measurementId: 'G-R4D701K5ZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6oWlh7yEXmhRUGqzQtAlNrDxR9y2czcw',
    appId: '1:258703453258:android:08753fb42f3143f06a0ab3',
    messagingSenderId: '258703453258',
    projectId: 'course-project-f4c51',
    storageBucket: 'course-project-f4c51.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLRrDd6KJxG7tqXm3f4sqCbHBfO4_XHb8',
    appId: '1:258703453258:ios:1341601e4b6e4f166a0ab3',
    messagingSenderId: '258703453258',
    projectId: 'course-project-f4c51',
    storageBucket: 'course-project-f4c51.appspot.com',
    iosClientId: '258703453258-58jl2mmes1ak8ra7sqlpml5vddqub6d0.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLRrDd6KJxG7tqXm3f4sqCbHBfO4_XHb8',
    appId: '1:258703453258:ios:1341601e4b6e4f166a0ab3',
    messagingSenderId: '258703453258',
    projectId: 'course-project-f4c51',
    storageBucket: 'course-project-f4c51.appspot.com',
    iosClientId: '258703453258-58jl2mmes1ak8ra7sqlpml5vddqub6d0.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseProject',
  );
}
